http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # This upstream is for your main CI/CD service.
    upstream main_cicd_app {
        least_conn;
        server 127.0.0.1:8022;
    }

    # Main server block for your CI/CD service's public domain.
    server {
        listen 80;
        server_name localhost;

        location / {
            # Pass client information to the backend
            proxy_pass http://main_cicd_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;


            # Forward client browser and session information
            proxy_set_header User-Agent $http_user_agent;
            proxy_set_header Cookie $http_cookie;
            proxy_set_header Accept-Language $http_accept-language;
            proxy_set_header Referer $http_referer;


            #Forward client's authorization data 
            proxy_set_header Authorization $http_authorization;
        }
    }

    # 🔑 Dynamically generated sites go here
    include /etc/nginx/conf.d/*.conf;
}
